### PR TITLE
Extend olgm.layer.GoogleLayer from ol.layer.Layer instead of ol.layer.layerGroup.

### PR DESCRIPTION
**Pull request by mstenta**
See https://github.com/mapgears/ol3-google-maps/issues/37

### CODE REVIEW

**Comment by adube** [comment]
@mstenta Thanks for the patch.  Would you please take a look at why Travis' build is failing?  Thanks.

**Comment by mstenta** [comment]
Looking into that now... thanks! Also writing up some notes in the issue: https://github.com/mapgears/ol3-google-maps/issues/37

**Comment by mstenta** [comment]
I fixed the failing test by moving `const options = opt_options ? opt_options : {};` above the call to `super(options)`. This is following the pattern used in `ol/layer/Layer.js`.

**Comment by adube** [comment]
> I fixed the failing test by moving `const options = opt_options ? opt_options : {};` above the call to `super(options)`. This is following the pattern used in `ol/layer/Layer.js`.

Gotcha, thanks for the feedback.  I should be able to review/test this soon.

**Comment by adube** [comment]
Code is clean.  Patch tested and no issues were found.  Thanks a lot for the contribution!

**Review by adube — APPROVED** [review]

**Comment by mstenta** [comment]
Thanks for taking the time to review and merge @adube !

**Pull request merged**
