### PR TITLE
Upgrade to OpenLayers 4.2.0

### PR DESCRIPTION
**Pull request by bampakoa**
Upgrade according to release notes [4.2.0](https://github.com/openlayers/openlayers/releases/tag/v4.2.0)
Add VSCode special folder to .gitignore.

### CODE REVIEW

**Comment by adube** [comment]
Travis fails because of the node packages that are used in OpenLayers 4.2 are no longer supported in nodejs 4.

See the `.travis.yml` file, you'll see:

```
node_js:
  - "4"   # npm 2
  - "6"   # npm 3
```

Replace this for:

```
node_js:
  - "6.1"   # npm 3
  - "8"   # npm 5
```

Let's try node 8 and see if it builds as well.

Thank you very much.

**Review by adube — CHANGES_REQUESTED** [review]
See my previous comment.  Thanks a lot for this!

**Comment by bampakoa** [comment]
@adube Travis checks seems to have passed

**Comment by adube** [comment]
Everything looks good.  I'm merging this, now.  Thanks for the patch!

**Comment by bampakoa** [comment]
Awesome! I plan to submit a new PR for the next version of OpenLayers next week. I decided to submit separately so that we can follow the 1 on 1 rule between OLGM and OL versions 😏

**Comment by adube** [comment]
Excellent.  Meanwhile, I'll create a release.  I won't do too much noise about it though, as these are for past OL release.  I'll make an announcement when we upgrade to the latest, i.e. 4.5.0.  Again, thanks a lot!

**Comment by bampakoa** [comment]
Letting know about the release, would be beneficial for people that have not updated their OL version due to OLGM, like me 😃

**Pull request merged**
