### PR TITLE
Properly size the canvas based on image size and rotation angle

### PR DESCRIPTION
**Pull request by agpixdev**
The current implementation used for rendering images does not handle correctly images whose width or height exceed a default value (around 300 pixels in width/height). This results in the image being clipped when displayed. This is even more evident when the image is rotated as this increases the effective canvas size requirements.

The changes are fixes for this limitation. The fix is demonstrated in the modified version of the icon.html example. To see the effect, first run the updated version of the example without the fix applied. Then compare with the fix applied.

### CODE REVIEW

**Review by adube — CHANGES_REQUESTED** [review]
If you look at the icon.html example from your branch, you'll see that the small icon is clipped.

If you look at the same example from master, it's not clipped.

I haven't looked deeper at why, but would you please take a look to try to figure what's wrong?

Thanks.

**Comment by agpixdev** [comment]
OK, will check and get back to you. Thanks @adube !

**Comment by agpixdev** [comment]
This update now takes into account the anchor offsets, fixing the problem seen.

**Comment by adube** [comment]
Thanks.  I should be able to test the patch again this weekend.

**Review by adube — APPROVED** [review]
Code is clean.  Tested and it works properly now.  Thanks for this nice contribution!

**Comment by agpixdev** [comment]
Merci Alexandre ! Thanks for providing and maintaining this library for the community !

**Comment by adube** [comment]
Thanks :)

Thanks to you and every contributor as well!

**Pull request merged**
