### PR TITLE
Upgrade to OpenLayers 4.3.4

### PR DESCRIPTION
**Pull request by bampakoa**
Upgrade according to release notes [4.3.0](https://github.com/openlayers/openlayers/releases/tag/v4.3.0)

### CODE REVIEW

**Comment by adube** [comment]
Let's use `4.3.4` instead as it includes more bug fixes.  Let's do this for the other releases as well, i.e.: `4.4.2`, `4.5.0`, etc.

**Review by adube — CHANGES_REQUESTED** [review]
See comment above.

**Comment by bampakoa** [comment]
@adube it's ready

**Comment by adube** [comment]
Yep, I'll do a review today.  Thanks for the reminder.

**Review by adube — APPROVED** [review]

**Comment by adube** [comment]
@bampakoa Thanks again for the patch.  I'll proceed with a new release.

**Comment by adube** [comment]
@bampakoa I'm done.

**Pull request merged**
