### PR TITLE
Support OpenLayers 6+

### LINKED ISSUE #282: Support for OpenLayer 6+
OpenLayers 6 removes the `LayerType.js` file that we reference in `src/olgm/layer/Google.js`: https://github.com/mapgears/ol3-google-maps/blob/master/src/olgm/layer/Google.js#L4

This results in an error when using this with Webpack:

```
ERROR in ./node_modules/olgm/layer/Google.js
Module not found: Error: Can't resolve 'ol/LayerType.js' in '/usr/src/app/node_modules/olgm/layer'
 @ ./node_modules/olgm/layer/Google.js 4:0-40 44:16-25
 @ ./src/instance/methods/google.js
 @ ./src/instance/instance.js
 @ ./src/main.js
```

### PR DESCRIPTION
**Pull request by mstenta**
See https://github.com/mapgears/ol3-google-maps/issues/282

### CODE REVIEW

**Comment by mstenta** [comment]
This is ready for review!

I'm doing some more manual testing, but things seem to be working well!

**Comment by adube** [comment]
Thanks.  I should be able to review this before the end of the week.

**Review by adube — APPROVED** [review]
Tested: everything's working fine!  Thanks a lot for the patch.

**Comment by sudarshanuprety42** [comment]
With olgm+openlayer 6, Interaction on map(zoom, scroll) not working properly. Can anyone help

**Pull request merged**
