### PR TITLE
Support for MultiLineString

### PR DESCRIPTION
**Pull request by LSG8**
I Modified the gm.js for multilinestring as Multipolygon is included in pull request #180  
But it is not working with multilinestring.

### CODE REVIEW

**Review by adube — CHANGES_REQUESTED** [review]
gm.js seems to be a copy of olgm/gm.js.  Please, remove.

Also, please make sure that you run `make lint` and `make dist` to ensure that there are no errors reported.

I haven't look at the changes themselves yet.  I'll leave that when the build is green.

**Comment by LSG8** [comment]
Yes, gm.js is a copy. How to remove? I am new user of github. I wanted to remove it and to keep only the edited file. But did not able to do. I did `make dist` and it did not give any error with the edited file.

**Comment by adube** [comment]
@LSG8 Please, look for git and GitHub tutorials to gain more knowledge before providing a patch.  Also, See the error reported by Travis, i.e. see https://travis-ci.org/mapgears/ol3-google-maps/builds/302924445?utm_source=github_status&utm_medium=notification

**Comment by adube** [comment]
If I may also point out:

 * you should only include the support of MultiLineString in this PR, as there's already an exiting PR for the MultiPolygon.  Please, remove the code you copied from the other PR.
 * please, provide an example that show the multilinestring working.  Label it "multi geometries" for it to be edited in the future to show the support of all types of supported multi geometries.

Thanks

**Pull request closed without merging**
