### PR TITLE
Support for MultiLineString

### PR DESCRIPTION
**Pull request by LSG8**
I want to add support for MultilineString for ol3 google map. I changed the src/olgm/gm.js file as required and then tried with `make dist`. But it is not working. Please help.

### CODE REVIEW

**Comment by bampakoa** [comment]
@LSG8 what error do you get when running `make dist`?

**Comment by LSG8** [comment]
It ran fine. No error was there.

**Comment by adube** [comment]
@LSG8 Please, add an example with this PR.

**Comment by adube** [comment]
@LSG8 I had asked for a "MultiGeometry" example, remember?  But nevermind that.  Yesterday, the PR that introduces the MultiPolygon added some features with MultiPolygons inside the "concept" example, which is a good idea.

I'm sorry to ask you this, but would you please wait for the MultiPolygon PR to be merged, then rebase your work on top of the master branch and finally move your code that demonstrates the MultiLineString support inside the "concept" example as well?  This would mean to remove the "multilinestring" example.

Thanks for your comprehension.

**Comment by LSG8** [comment]
@adube Ok, but the first thing is that my modification on gm.js does not help to support multilinestring. That is what I first told in my first comment. In my example also, OSM supports multilinestring but not googlemap. I need help in that case first. If that works then only I will add it to concept example. Is not it so?

**Comment by adube** [comment]
Oh... now I get it.  You made a PR with something that doesn't work and you're asking for help to make it work.  OK.

I'm hesitant to leave this PR opened.  It kinda odd to have a PR that doesn't work... I'll leave it opened in case someone wants to jump in and fix what's wrong with your code.  Thanks.

**Comment by LSG8** [comment]
That's why I first made a comment stating the problem on the multipolygon PR before creating this PR.

**Comment by adube** [comment]
Yes, but then you went ahead and created a PR.  At first, I thought you figured it out.  I did not understand what you meant by "it did not work".  I was confused because, normally, you don't provide a patch to a project that does not work and where you're asking for help.  It's no biggie, really.  Now that the confusion's behind us, you can focus on making it work.

**Comment by LSG8** [comment]
Then what should be my next step? Can you please help me after checking the code? Or anyone else?

**Comment by adube** [comment]
I currently can't.

**Comment by adube** [comment]
MultiLineStrings have been introduced in #180.  Closing this PR.

**Pull request closed without merging**
