### PR TITLE
Exclude OL from OLGM bundling

### PR DESCRIPTION
**Pull request by agpixdev**
In a legacy ES5 environment without transpiling support, the current bundling of the OpenLayers library with OLGM seems to be missing some elements of OpenLayers (as if only actual parts of OpenLayers directly used by OLGM are included). In order to inject the missing parts of OL in the application, one needs to include it directly. This is creating issues since part of the OL runtime becomes effectively duplicated.

The goal of this PR is to have the OpenLayers library be treated as an external dependency such that no part of it is bundled in the olgm.js file prepared as the output from the build-legacy build path.

Some npm dependencies are also updated to later versions.

### CODE REVIEW

**Comment by adube** [comment]
It is true that we no longer provide a JS bundle of OLGM, and the one that is actually built only includes the portions it needs from OL to work.

If I recall correctly (and after looking at the code a little), OLGM doesn't use code exported by OL that is not marked as @api.  Such methods, for example `ol.events.listen`, are exported by OL so if one uses modules and imports OL one would be able to import `ol.events.listen`, but they are not marked as `@api` and if one uses the JS bundle provided by OL then `ol.events.listen` is not there.

Things have changed with modules, so the actual above namespace for the method is no longer true (but you get the idea).

Where am I going with this?  I think this change makes sense and should work as a way to provide a bundle of OLGM for people still using ES5 environments, without depending on OL.

I would like to see this in a demo, i.e. use a bundle with a bundle of OL alongside a bundle of OLGM and show that it actually works before accepting this.

Finally, the tests would need to be fixed accordingly.

Thanks a lot for the contribution!

**Comment by agpixdev** [comment]
Hi Alexandre,

Thanks for the review. Here is the example requested. I have also fixed the build (actually reverted to your previous package.json & package-lock.json files).
[example.zip](https://github.com/mapgears/ol3-google-maps/files/3298558/example.zip)

**Comment by adube** [comment]
I tried the example.  While running it, I noticed errors being thrown in the browser's console.

I went and checked your original branch and ran the "concept" example and saw the same errors there.  On master branch, there's none.

I tried to rebase your branch onto master and the errors are gone.  Would you please rebase your branch onto master and update the PR, please?  It would also be nice if you could update the bundled js file in your example.

I also noticed that you removed (commented) "uglify".  Would you please restore it?

Thanks.

**Review by adube — CHANGES_REQUESTED** [review]
(see above comment)

**Comment by agpixdev** [comment]
Hi Alexandre,

Please find attached an updated example (the data folder containing an icon was missing in the last and causing one of the error seen). This also uncovered an issue in the PropertyListener class (typo in unlisten method). I have committed a fix for this and re-enabled the uglify build pass as requested.

Thanks !

[example.zip](https://github.com/mapgears/ol3-google-maps/files/3302077/example.zip)

**Comment by adube** [comment]
I'm still hesitant towards this one.  Looking at the changes, to me it seems like we would need to always manually add whatever we need to include from OL from now on, which is kinda annoying.

Also, I agree with [JamieWhiteShirts' comment]( https://github.com/mapgears/ol3-google-maps/pull/257#issuecomment-530824025), which increases my thoughts on the matter: maybe we should not include this patch.  I don't strongly disagree, but would like to hear your thoughts.

Thanks again!

**Comment by agpixdev** [comment]
I also agree with JamieWhiteShirts' comment you refer to (see above). Moving away from ES legacy bundles (OLGM+OL in this case) and using ES modules is the way to go. However, for legacy projects, this might not be possible (or not a priority). My own experience with the existing build-legacy output is that I got some unresolved OL references when using the OLGM+OL bundle. That was done for a client a while ago, so unfortunately I don't recall the details of what was missing (but could try reproducing it if required).

Another reason keeping OLGM separate from OL is that it's easier to update the OL side for example following a new maintenance release for OL since they are now separate.

Regarding the rollup.js changes, being no rollup expert, it's quite possible that a more straightforward implementation (using wildcards or something similar) could achieve the same result without introducing the more detailed externals listed in the submission. The general idea here is to mark all entrants coming from OL as external to the bundle (OLGM) being built.

I understand your hesitation regarding this change, but I believe it's bringing in more flexibility to developers (at a small expense). Given that longer-term the build-legacy option will fade out, I believe this is a reasonable time-limited trade-off for the benefits of obtaining a dist version of the OLGM library (if I read that correctly, I believe this would also provide a solution for the request in https://github.com/mapgears/ol3-google-maps/pull/257#issuecomment-530807004).

If you decide not to merge this change, we'll just keep the modification on our side, so it's not a big deal. Just thought others in the community might be in the same situation and it could help them.

Thanks Alexandre !

**Comment by adube** [comment]
The OLGM library is now deprecated.  See: https://github.com/mapgears/ol3-google-maps/pull/352

**Pull request closed without merging**
