### PR TITLE
Attempt to upgrade to OpenLayers 4.1.1

### PR DESCRIPTION
**Pull request by hawkaa**
Hi there,

This PR attempts to update ol3-google-maps to OpenLayers 4.1.1 and closure-util 1.18.0. I hope the changes looks good.

However, I'm getting some errors when trying to run the tests:
```
node tasks/test.js
/Users/hawk/code/ol3-google-maps/node_modules/closure-util/lib/manager.js:186
              throw new Error('Unsatisfied dependency "' + require + '" ' +
              ^

Error: Unsatisfied dependency "ol" in script: /Users/hawk/code/ol3-google-maps/src/gm/maplabel.js
    at /Users/hawk/code/ol3-google-maps/node_modules/closure-util/lib/manager.js:186:21
    at Array.forEach (native)
    at visit (/Users/hawk/code/ol3-google-maps/node_modules/closure-util/lib/manager.js:183:25)
    at /Users/hawk/code/ol3-google-maps/node_modules/closure-util/lib/manager.js:190:13
    at Array.forEach (native)
    at visit (/Users/hawk/code/ol3-google-maps/node_modules/closure-util/lib/manager.js:183:25)
    at /Users/hawk/code/ol3-google-maps/node_modules/closure-util/lib/manager.js:212:11
    at Array.forEach (native)
    at Manager.getDependencies (/Users/hawk/code/ol3-google-maps/node_modules/closure-util/lib/manager.js:205:34)
    at Server._requestListener (/Users/hawk/code/ol3-google-maps/node_modules/closure-util/lib/server.js:153:32)
```

I'd appreciate any feedback I could get on the above.

What do you think?

Håkon

### CODE REVIEW

**Comment by adube** [comment]
Hello @hawkaa.  Thanks for working on this.

In the last minutes, I've been trying to figure out what's wrong but couldn't.  I'll seek help from the OpenLayers community.

**Comment by adube** [comment]
See: https://groups.google.com/forum/#!topic/openlayers-dev/oIC2FIS6uRY

**Comment by hawkaa** [comment]
Much appreciated! Let's see if we can get any useful help. And thanks for replying so quickly.

**Comment by adube** [comment]
Btw, I noticed that when running the examples, i.e. when doing `make serve` and visiting any example we get the same error.

**Comment by hawkaa** [comment]
@adube The build is green now 👍 Se commit #31bc088 . I am not sure what else there is to be done to get this merged. Could you do a brief look and see if it looks alright? I suppose we need to update the version number of `openlayers3-google-maps` as well, but I'm not sure how I do that.

**Comment by adube** [comment]
Hello @hawkaa.

Thanks for your work on this upgrade.  I looked at the examples and didn't see anything major that changed since the last version so I think we're good to go with this.   Thank you.

About the version number: let me take care of this.  For the record, making a new release is described here: https://github.com/mapgears/ol3-google-maps/blob/master/RELEASE.md.  The commit access to this repository and NPM are required to do that.  That's why I'll take care of it.

**Comment by adube** [comment]
@hawkaa olgm 0.14.0, which includes your fix, is released.  Thanks again for your work.

**Comment by hawkaa** [comment]
Thanks for all help!

**Pull request merged**
