### PR TITLE
Track changes made to feature style

### PR DESCRIPTION
**Pull request by agpixdev**
Track updates to feature styles during the lifetime of a feature. Right now the olgm library only tracks the style at the creation time of a feature. Any update to a feature style is not reflected by the feature herald later on. The goal of this PR is to add this capability. Note that since OpenLayers does not explicitly send change events for styles, we have to rely on the generic change event at the feature level.

### CODE REVIEW

**Comment by adube** [comment]
Sorry it is taking long @agpixdev to review this patch.

Would you please create a small test case to reproduce the issue, which could be tested with your patch to demonstrate it being fixed?  It can be a chunk of code to add to an existing example (temporarily)

**Comment by agpixdev** [comment]
Thanks @adube ! I have modified the concept.js example to show the behavior of the style tracking changes submitted. Let me know if this is OK.

**Comment by adube** [comment]
@agpixdev Excellent.  I'll have a look at this during weekend.

**Comment by adube** [comment]
Code is clean.  Tested through the "concept" example and it works well.  Thank you very much for this enhancement!

**Comment by agpixdev** [comment]
Thanks for the merge @adube.

**Pull request merged**
