### PR TITLE
OpenLayers 5 support, olgm package, workflow changes and ES modules

### PR DESCRIPTION
**Pull request by JamiesWhiteShirt**
This is a massive refactoring of ol3-google-maps to support OpenLayers 5, while at the same time inheriting other advancements of the OpenLayers development workflow.

The OpenLayers migration to version 5 has served as a guide for ours. The path of least resistance was to inherit their workflow rather than adapt the current one. I can understand how it could be a big undertaking to support OL-Google-Maps with all these changes and new things to learn, so I am willing to make changes to suit your preferences.

# Notable changes
* ES6 features, namely modules, classes and arrow functions.
* The setup is simpler - no dependency on Java, Python or Make.
* Deprecation of the name OL3-Google-Maps in favor of OL-Google-Maps. The major version of OpenLayers is no longer significant. I found this to be a good opportunity to change it.
* Deprecation of the `ol3-google-maps` package in favor of a new `olgm` package.
* `olgm` declares `ol` as a peer dependency, meaning `olgm` users can use new versions of `ol` straight away without waiting for `olgm` to update and bundle the new version.
* The Google Maps API key used to testing and examples is provided as the environment variable `GOOGLE_MAPS_API_KEY` instead of having to be written to scattered files. This makes the workflow better in terms of both simplicity and source control compatibility.
* No more Make - all tasks are performed with NPM scripts.
* JSDoc site generation, defined and rendered in the style of OpenLayers.
* Examples site generation, defined and rendered in the style of OpenLayers. [See OpenLayers examples](https://github.com/openlayers/openlayers/tree/master/examples)

# Not included

### Type checking
We currently have no type checking. A TypeScript type checking implementation is pending for OpenLayers. When it is ready we should be able to reuse the implementation. https://github.com/openlayers/openlayers/pull/8345

### Legacy bundles
OpenLayers distributes legacy builds of new versions behaving like the old closure bundles did. I expect that some users are interested in using OpenLayers 5 features with OL-Google-Maps as a legacy bundle.

It appears to be fairly straightforward to create legacy bundles containing both `ol` and `olgm`. This is not an ideal solution, because it requires keeping up with OpenLayers like we currently do.

Ideally, an `olgm` legacy bundle could live alongside an `ol` legacy bundle. This appears to be technically possible, however, implementing this isn't very straightforward, and is left to implement in the future.

### CODE REVIEW

**Comment by adube** [comment]
Awesome work, @JamiesWhiteShirt!  Everything looks really clean and I'm very happy with what I see. Here's a few comments.  Thank you very much for your work on this.

 * **olgm as new package name**: I agree
 * **Type Checking**: It's okay to not have anything for now and wait to see how OL is going to implement theirs and try to do the same
 * **Major release**: It would make sense to declare the next release as `1.0.0`
 * **Legacy bundle**: I agree that it's not ideal to have to distribute a legacy bundle. I suspect that if we do not do so, some people would ask for it.  I suggest to not do such a bundle right away, and if people are asking for it then we would create a separate task about it. Let me know what you think about it.

**Comment by hawkaa** [comment]
Amazing work @JamiesWhiteShirt . What is the status of this PR? Is it soon ready to be merged?

**Comment by JamiesWhiteShirt** [comment]
@adube Please excuse my delay, there were some other pressing matters that required my attention. I hope the delay hasn't hampered any further development of ol3-google-maps.

At the time of writing, OpenLayers still does not have type checking. I would like to help introduce this in ol3-google-maps when the time comes. I also think it should be OK to not have it for now, as OpenLayers appears to manage just fine.

Legacy bundles are not of interest to us, as it is not required for our workflow. We are certainly not opposed to leaving legacy bundles aside for someone to contribute in the future, if you think that is OK.

All examples except two are compiling and working to the best of my knowledge. "Latest Google Maps version" doesn't exactly do as promised at the moment. "OL-Google-Maps + ol-layerswitcher" isn't working properly. In fact, a few new examples showed up, namely "OL-Google-Maps + ol-layerswitcher" and "Overview map". Do know why they are missing from [http://mapgears.github.io/ol3-google-maps/examples/](http://mapgears.github.io/ol3-google-maps/examples/)?

The API docs are currently not perfect. Some internal (non-API) packages appear as empty packages in the docs.

What is currently on the roadmap is fixing the examples, checking for ol 4.x compatibility and applying any advancements that OpenLayers might have added to their build process since last time it was referenced.

**Comment by adube** [comment]
@JamiesWhiteShirt 

 * Type checking: Let's go without it.
 * Legacy bundles: I agree, let's leave them aside for now
 * The 2 examples that are not working: Let's move them in an archive directory for them to be excluded for now.  If we want to bring them back, the we would focus our efforts to make them work in a separate task.
 * API: Even if not perfect, that's fine

Excellent work, indeed!  Thank you very much.

**Comment by JamiesWhiteShirt** [comment]
I did as requested. I ended up making olgm compatible with `ol` ^4.0.0 || ^5.0.0. I have not actually verified compatibility with 4.0.0, but I think it should be fine.

I urge you to pull these locally and try them out, especially if you are on Mac or Linux, as this has only been tested on Windows. Remember to set the GOOGLE_MAPS_API_KEY environment variable before building/serving examples. I believe this should also be configured for Travis.

**Comment by adube** [comment]
I tested the new environment on Linux.  I was able to run the examples, run the linter properly, see changes in action, etc.  Excellent work.

@JamiesWhiteShirt If you agree, I'd merge this.

**Comment by JamiesWhiteShirt** [comment]
All right! Being a major refactoring, there is a pretty high probability of bugs. I would recommend doing something of a beta release first, then we can declare it as stable eventually. What do you think?

I will leave the versioning and releasing up to you.

**Comment by bampakoa** [comment]
@JamiesWhiteShirt I did not find time to test the PR but congrats for your job! You mentioned that you have tested it for Windows environment. Are there any changes for developing in Windows in relation with the previous README guide?

**Comment by JamiesWhiteShirt** [comment]
@bampakoa If you mean developing OLGM: It is much simpler now. The guide in the new DEVELOPING.md applies to all systems, including Windows. Python, Java and Make are no longer required. Node 8 is required.

If you mean using OLGM: I don't think so.

**Comment by adube** [comment]
There are some changes to make to the release procedure.  I'm going to make a small PR about this first.

**Comment by adube** [comment]
Release completed.  See:

 * Announcement: https://groups.google.com/forum/#!topic/openlayers-dev/SnWl0N56N90
 * NPM package: https://www.npmjs.com/package/olgm
 * Release notes: https://github.com/mapgears/ol3-google-maps/releases/tag/v1.0.0-beta.2

Thanks to all contributors!

**Comment by boomdrak** [comment]
We have been using beta4 in our production environment for a months time now.
No issues or bugs met upon at this time.

Good work! :)

**Pull request merged**
