### PR TITLE
fixes #37

### LINKED ISSUE #37: ol3-layerswitcher compability
Hi! Has anyone here used `ol3-layerswitcher` together with `ol3-google-maps`? For some reason the google layer doesn't show correctly in my layer switcher:

screen shot 2016-01-18 at 15 37 02

Relevant pieces of code:

```
    var map = new ol.Map({
      target: 'map',
    });

    var googleLayer = new olgm.layer.Google({
      title: 'Kart (Google)',
      type: 'base',
    })
    map.addLayer(googleLayer);

    var shadedBing = new ol.layer.Tile({
      title: 'Kart (Bing)',
      type: 'base',
      source: new ol.source.BingMaps({
        key: bingKey,
        imagerySet: 'Road'
      })
    });
    map.addLayer(shadedBing);

    ...

    map.setView(new ol.View({
        projection: 'EPSG:900913',
        center: ol.proj.transform(
          settings.coords,
          'EPSG:4326',
          'EPSG:900913'
        ),
        zoom: 14
    }));

    var layerSwitcher = new ol.control.LayerSwitcher({});
    map.addControl(layerSwitcher);

    var olGM = new olgm.OLGoogleMaps({map: map});
    olGM.activate();

```

Any thoughts?

### PR DESCRIPTION
**Pull request by geopamplona**
Possible solution to #37 ... for the moment this is a valid solution for me .. I do not know if it is for everyone.
I have tested it in moz, ie, chrome; Everything is still working properly osm + gm = OK 
i try load other wmts sources, all is ok
Pd: is my first contribution to the code, I do not know if it is a solution or chance

### CODE REVIEW

**Comment by adube** [comment]
See https://github.com/mapgears/ol3-google-maps/blob/master/DEVELOPING.md to learn how to contribute a clean patch.

Thanks for your contribution.

**Comment by adube** [comment]
Run `make check` in your local dev env. to be able to see the errors.

**Comment by geopamplona** [comment]
Everything seems correct.
I had problems with the code style.

**Comment by adube** [comment]
I looked at your patch and I was curious how it could affect the issue reported in #37, i.e. the fact that the Google layer does not show its radio button.

So, I went and added an example featuring the ol3-layerswitcher alongside ol3-google-maps (see #166).  Then, I applied your patch and it did not fix the issue.

I wonder if you're referring to the correct issue.  Your patch features something in the vector feature herald.  It's not supposed to have anything to do with the issue reported in #37.

Would you please clarify exactly what the issue you had and how your patch fixes it?  Thanks.

**Comment by geopamplona** [comment]
It's true that you're right I've explained myself wrong ..
Actually # 37 has no relationship with my solution ...
I expose my case
I try to use ol3-layerswitcher with ol3-google-maps;
I use both libraries in recent download versions
When loading both libraries the google layers are shown correctly, in the layer selector .. they exchange the layers well and everything is correct ..
But when adding another layer like osm or vector layers these also appear correctly (it does not really have relation with # 37)
But when I select osm layer or a vector layer the application returns an error and the operation of the script stops being normal; The error is as follows:
TypeError: this.cache_ [index] is undefined [Learn more] ol3gm-debug.js: 83477: 5
Olgm.herald.VectorFeature.prototype.unwatchFeature_ ol3gm-debug.js: 83477: 5
For-self self-hosted
Olgm.herald.VectorFeature.prototype.deactivate ol3gm-debug.js: 83393: 3
Olgm.herald.VectorSource.prototype.deactivateCacheItem_ ol3gm-debug.js: 83663: 3
For-self self-hosted
Olgm.herald.VectorSource.prototype.deactivate ol3gm-debug.js: 83651: 3
Olgm.herald.Layers.prototype.deactivateGoogleMaps_ ol3gm-debug.js: 91469: 3
Olgm.herald.Layers.prototype.toggleGoogleMaps_ ol3gm-debug.js: 91516: 5
Ol.events.bindListener_ / boundListener ol3gm-debug.js: 3431: 12
Ol.events.EventTarget.prototype.dispatchEvent ol3gm-debug.js: 3849: 11
Ol.Object.prototype.notify ol3gm-debug.js: 4262: 3
Ol.Object.prototype.set ol3gm-debug.js: 4282: 7
Ol.layer.Base.prototype.setVisible ol3gm-debug.js: 20531: 3
Ol.control.LayerSwitcher.prototype.setVisible _ / <ol3-layerswitcher.js: 158: 21
Ol.control.LayerSwitcher.forEachRecursive / <ol3-layerswitcher.js: 243: 13
For-self self-hosted
Ol.Collection.prototype.forEach ol3gm-debug.js: 12408: 3
Ol.control.LayerSwitcher.forEachRecursive ol3-layerswitcher.js: 242: 9
Ol.control.LayerSwitcher.prototype.setVisible_ ol3-layerswitcher.js: 156: 13
Ol.control.LayerSwitcher.prototype.renderLayer_ / input.onchange

I add the layers on the map like this:
Layers: [
base,
New olgm.layer.Google ({
Title: 'NORMAL (Google)',
// visible: true,
Type: 'base',
Combine: true}),
New olgm.layer.Google ({
MapTypeId: google.maps.MapTypeId.SATELLITE,
Title: 'SATELLITE (Google)', type: 'base', combine: true
}),
New olgm.layer.Google ({
MapTypeId: google.maps.MapTypeId.TERRAIN,
Title: 'TERRAIN (Google)', type: 'base', combine: true
})
]

And the osm layer is defined as follows:

    Var base = new ol.layer.Tile ({
        Title: 'OSM (OpenStreetMap)',
        Name: lang.getLayerNames.OpenStreetMap,

// baselayer: true,
// combine: true,
Type: 'base',
Source: new ol.source.OSM (),
});

Everything looks correctly declared but does not work correctly in my code ...
This error corrected it with my solution ... maybe I should have created a new case before commenting on the # 37 .. I apologize to you and the entire community of mapgears / ol3-google-maps for making you waste time on this .. .

If it is correct or I do not know it, but for me it is a solution, now I change the layer selection to osm or another layer and I have no error, and therefore the execution is correct and everything works correctly ..

(It looks like an error associated with clearing the cache of vector elements)

I've seen few comments on this, maybe all of them work correctly with gm + osm integration using mapgears / ol3-google-maps and ol3-layerswitcher and it just failed me ... anyway I've gone from a bug to The solution for me is valid for now has not failed ... thanks !

**Comment by adube** [comment]
Thanks for the explanation, @geopamplona.

We'll have to test/debug what you're describing more.  We won't merge your patch without testing.  For now, here's what I suggest: you should create a branch in which you have you patch in a single commit.  I suggest you do this instead of your `master` branch.  Then, create your own builded version.  From time to time, for example when olgm releases a new version, rebase your master branch onto the olgm master branch, rebase your branch with the patch then re-create your own builded version.

It shouldn't be too much efforts and that would let you keep your version up-to-date.

We should be able to work on this a couple of months.  For the time being, cheers.

**Pull request closed without merging**
